@enum GrB_Info begin
    GrB_SUCCESS = 0
    GrB_NO_VALUE = 1
    GrB_UNINITIALIZED_OBJECT = 2
    GrB_INVALID_OBJECT = 3
    GrB_NULL_POINTER = 4
    GrB_INVALID_VALUE = 5
    GrB_INVALID_INDEX = 6
    GrB_DOMAIN_MISMATCH = 7
    GrB_DIMENSION_MISMATCH = 8
    GrB_OUTPUT_NOT_EMPTY = 9
    GrB_OUT_OF_MEMORY = 10
    GrB_INSUFFICIENT_SPACE = 11
    GrB_INDEX_OUT_OF_BOUNDS = 12
    GrB_PANIC = 13
end

@enum GrB_Mode begin
    GrB_NONBLOCKING = 0
    GrB_BLOCKING = 1
end